baseURL: https://fightcovid.dev
languageCode: en-us
title: FightCovid
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Fight Covid-19
    # Hero subtitle (optional)
    subtitle: Real-time Collaboration for Doctors World-Wide
    # Button text
    buttontext: Use Now
    # Where the main hero button links to
    buttonlink: "https://broker.apibill.me"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
  section2:
    title: Real-time Collaboration
    subtitle: with the medical community
    features:
    - title: World-Wide Messaging
      text: Get the information you need
      icon: laptop-globe
    - title: Secure and Real-time 
      text: End to End Encryption, Anonymous, and real-time messaging
      icon: doc-sync
    - title: Built on Open Source
      text: No lock-in and free to use
      icon: mobile-feed
  section3:
    title: Live Today
    subtitle: No Login Required
    buttonText: Use Now
    buttonLink: "https://broker.apibill.me"
    