baseURL: https://apibill.me
languageCode: en-us
title: The API Answer
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Broker
    # Hero subtitle (optional)
    subtitle: Real-time Zero Code API Server
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://crates.io/crates/broker"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
  navbar:
    - title: Start Now
      url: https://github.com/apibillme
      button: false
  section1:
    title: Build web apps
    subtitle: Super fast
    tiles:
    - title: Broker
      icon: auth0-blue
      text: Real-time Zero-Code API
      url: https://crates.io/crates/broker
      buttonText: View
    - title: Tarp
      icon: stripe-black
      text: Rust Code Coverage
      url: https://crates.io/crates/tarp
      buttonText: View
  section2:
    title: Build Web Apps Fast
    subtitle: Front-end Coding Only
    features:
    - title: Zero Backend Code
      text: Write only front-end code
      icon: laptop-globe
    - title: Real Time Evented Stream
      text: Uses SSE, immutable events, and user authentication
      icon: doc-sync
    - title: Deploy to your platform of choice
      text: Linux via Snap or Compile with Rust
      icon: mobile-feed
  section3:
    title: Build Fast
    subtitle: Starting now
    buttonText: Get started
    buttonLink: "https://crates.io/crates/broker"
  section4:
  footer: