baseURL = "https://apibill.me"
languageCode = "en-us"
title = "apibillme"
theme = "hugo-fresh"

[params]

  [params.font]
  name = "Open Sans"
  sizes = [
    400.0,
    600.0
  ]

  [params.hero]
  title = "Simple API Monetization"
  subtitle = "Start billing today!"
  buttontext = "Get started"
  buttonlink = "https://github.com/apibillme/apibillme-gateway"
  image = "illustrations/worker.svg"

  [params.section1]
  title = "Bill your API users"
  subtitle = "built on affordable platforms"

    [[params.section1.tiles]]
    title = "Free Account"
    icon = "auth0-blue"
    text = "Identity provider"
    url = "https://auth0.com"
    buttonText = "Sign up"

    [[params.section1.tiles]]
    title = "Pay As You Go"
    icon = "stripe-black"
    text = "Billing provider"
    url = "https://stripe.com"
    buttonText = "Sign up"

    [[params.section1.tiles]]
    title = "Open Source"
    icon = "krakend"
    text = "API gateway"
    url = "http://krakend.io"
    buttonText = "Check it out"

  [params.section2]
  title = "Make money quick"
  subtitle = "All the features hand-rolled just for you"

    [[params.section2.features]]
    title = "Powerful open-source API Gateway"
    text = "Built on KrakenD the fastest open-source API gateway that has the best features - like rate limting, OpenCensus, CORS, caching, no database(s), and more."
    icon = "laptop-globe"

    [[params.section2.features]]
    title = "User Management and API Billing"
    text = "Full integration with Auth0 and Stripe - including Auth0 OIDC JWTs, Auth0 RBAC OAuth2 scopes, and Stripe subscriptions."
    icon = "doc-sync"

    [[params.section2.features]]
    title = "Deploy to your platform of choice"
    text = "Supports Docker (all features), Bare Metal Linux (all features), and Apex Up on AWS Lambda (most features)."
    icon = "mobile-feed"

  [params.section3]
  title = "Bill today"
  subtitle = "Really you can!"
  buttonText = "Get started"
  buttonLink = "https://github.com/apibillme/apibillme-gateway"