baseURL: https://fightcovid.dev
languageCode: en-us
title: FightCovid
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Fight Covid-19
    # Hero subtitle (optional)
    subtitle: Real-time Collaboration for Doctors World-Wide
    # Button text
    buttontext: Fund Now
    # Where the main hero button links to
    buttonlink: "https://www.gofundme.com/f/fightcovid?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
  section2:
    title: Real-time Collaboration
    subtitle: with the medical community
    features:
    - title: World-Wide Chat
      text: Get the information you need
      icon: laptop-globe
    - title: Verified and Approved Users
      text: Only medical professionals
      icon: doc-sync
    - title: Built on Open Source
      text: Secure and Fast
      icon: mobile-feed
  section3:
    title: Fund Today
    subtitle: Taking Donations
    buttonText: Fund Now
    buttonLink: "https://www.gofundme.com/f/fightcovid?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1"
  section4:
  footer: